### ISSUE TITLE
Any results?

### ISSUE THREAD

**Issue by lucasjinreal** [bhavikngala/object_detection_in_point_clouds#1]
Does there any results or not?

**Comment by bhavikngala** [comment]
Hi, you can see some results over here: https://github.com/bhavikngala/object_detection_in_point_clouds/tree/doogal/results
But so far I havent been able to match the network performance from the paper. I hope to get the desired results soon.
Thanks.

**Comment by chowkamlee81** [comment]
Do you have update on the improved version of results?

**Comment by bhavikngala** [comment]
No, I haven't worked on it in some time now.
